[2022-11-18T23:32:14.830+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.Drop_Tables manual__2022-11-18T23:32:11.526013+00:00 [queued]>
[2022-11-18T23:32:14.855+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.Drop_Tables manual__2022-11-18T23:32:11.526013+00:00 [queued]>
[2022-11-18T23:32:14.856+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T23:32:14.858+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T23:32:14.860+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T23:32:14.894+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): Drop_Tables> on 2022-11-18 23:32:11.526013+00:00
[2022-11-18T23:32:14.909+0000] {standard_task_runner.py:55} INFO - Started process 1012 to run task
[2022-11-18T23:32:14.923+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Call_Center_ETL_DAG', 'Drop_Tables', 'manual__2022-11-18T23:32:11.526013+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_database_tables.py', '--cfg-path', '/tmp/tmp5jzhvdga']
[2022-11-18T23:32:14.930+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask Drop_Tables
[2022-11-18T23:32:15.116+0000] {task_command.py:376} INFO - Running <TaskInstance: Call_Center_ETL_DAG.Drop_Tables manual__2022-11-18T23:32:11.526013+00:00 [running]> on host b6a63ce50866
[2022-11-18T23:32:15.271+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abdelrhman Yassein
AIRFLOW_CTX_DAG_ID=Call_Center_ETL_DAG
AIRFLOW_CTX_TASK_ID=Drop_Tables
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T23:32:11.526013+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T23:32:11.526013+00:00
[2022-11-18T23:32:15.273+0000] {mysql.py:84} INFO - Executing: 
    DROP TABLE IF EXISTS staging_call;
    DROP TABLE IF EXISTS call_info;
    DROP TABLE IF EXISTS call_fact;
    DROP TABLE IF EXISTS customers;
    DROP TABLE IF EXISTS call_time;
    
[2022-11-18T23:32:15.323+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 86, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 165, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_conn_id` isn't defined
[2022-11-18T23:32:15.346+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Call_Center_ETL_DAG, task_id=Drop_Tables, execution_date=20221118T233211, start_date=20221118T233214, end_date=20221118T233215
[2022-11-18T23:32:15.408+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task Drop_Tables (The conn_id `mysql_conn_id` isn't defined; 1012)
[2022-11-18T23:32:15.465+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T23:32:15.667+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
