[2022-11-20T13:15:51.274+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.insert_fact_call_data manual__2022-11-20T13:15:12.651027+00:00 [queued]>
[2022-11-20T13:15:51.389+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.insert_fact_call_data manual__2022-11-20T13:15:12.651027+00:00 [queued]>
[2022-11-20T13:15:51.391+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T13:15:51.393+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-20T13:15:51.395+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T13:15:51.526+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): insert_fact_call_data> on 2022-11-20 13:15:12.651027+00:00
[2022-11-20T13:15:51.593+0000] {standard_task_runner.py:55} INFO - Started process 912 to run task
[2022-11-20T13:15:51.735+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Call_Center_ETL_DAG', 'insert_fact_call_data', 'manual__2022-11-20T13:15:12.651027+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/call_center_dag.py', '--cfg-path', '/tmp/tmph26g3lyc']
[2022-11-20T13:15:51.754+0000] {standard_task_runner.py:83} INFO - Job 173: Subtask insert_fact_call_data
[2022-11-20T13:15:52.270+0000] {task_command.py:376} INFO - Running <TaskInstance: Call_Center_ETL_DAG.insert_fact_call_data manual__2022-11-20T13:15:12.651027+00:00 [running]> on host 9eba6bc17a61
[2022-11-20T13:15:52.761+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abdelrhman Yassein
AIRFLOW_CTX_DAG_ID=Call_Center_ETL_DAG
AIRFLOW_CTX_TASK_ID=insert_fact_call_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-20T13:15:12.651027+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-20T13:15:12.651027+00:00
[2022-11-20T13:15:52.782+0000] {mysql.py:84} INFO - Executing: 
        INSERT INTO call_fact(call_id,customer_id,call_date,csat_score,call_in_minutes)
        SELECT DISTINCT
            st.id as call_id,
            c.customer_id ,
            STR_TO_DATE(call_timestamp, '%m/%d/%Y') AS call_date,
            CASE
                WHEN st.csat_score = ' ' THEN 1
                WHEN st.csat_score = 0 THEN 1
            END AS  csat_score,
            call_minutes
        FROM 
            staging_call st
        join customers c 
        on st.customer_name = c.customer_name
        WHERE
            id IS NOT NULL;
        
[2022-11-20T13:15:52.841+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-20T13:15:52.964+0000] {sql.py:315} INFO - Running statement: 
        INSERT INTO call_fact(call_id,customer_id,call_date,csat_score,call_in_minutes)
        SELECT DISTINCT
            st.id as call_id,
            c.customer_id ,
            STR_TO_DATE(call_timestamp, '%m/%d/%Y') AS call_date,
            CASE
                WHEN st.csat_score = ' ' THEN 1
                WHEN st.csat_score = 0 THEN 1
            END AS  csat_score,
            call_minutes
        FROM 
            staging_call st
        join customers c 
        on st.customer_name = c.customer_name
        WHERE
            id IS NOT NULL;
        , parameters: None
[2022-11-20T13:16:00.529+0000] {sql.py:324} INFO - Rows affected: 32941
[2022-11-20T13:16:00.630+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Call_Center_ETL_DAG, task_id=insert_fact_call_data, execution_date=20221120T131512, start_date=20221120T131551, end_date=20221120T131600
[2022-11-20T13:16:00.767+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-20T13:16:00.893+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
